### ISSUE TITLE
Madagascar Malaria report bug

### ISSUE THREAD

**Issue by johnhaskew** [meerkat-code/meerkat_frontend#135] opened 2016-08-21 09:26 UTC
The number of RDT positive / negative in Table 1 doesn’t tally with the total case of simple malaria (see attached). Could we please verify.

[malaria-report.pdf](https://github.com/meerkat-code/meerkat_frontend/files/428763/malaria-report.pdf)

**Comment by johnhaskew** [comment] 2016-08-24 18:44
Has this been sorted out yet?

**Comment by mrjb** [comment] 2016-08-27 15:32
Ok I think I've figured out the cause of this. There was a secondary condition of "intro./visit" to be "new" for some of the malaria codes but not for all (where the secondary condition was needed to calculate other factors).  This will have meant that the calculations were being performed for different records, which could have caused the discrepancies. The data at the moment doesn't reveal the discrepancy though... Anyway I'm redeploying as we speak.

**Comment by mrjb** [comment] 2016-08-27 18:10
Hmm... Not managed to deploy Madagtascar, tried a couple of times but Deploy script keeps hanging half way through.  Not got time to try and debug it at the moment.  This is pushed to master though so should be fixed in the next deploy.  I am away now for a couple of days, back Tuesday afternoon - if someone gets a chance to try and redeploy Madagascar before then (@Gulfa?) that would be good.

**Comment by mrjb** [comment] 2016-10-25 12:41
Just having another look over this.  The malaria report seems to have suffered a bit from the new codes file structure. I've been going over it trying to get it fixed up again and have noticed that there are no "RDT=negative" cases of malaria, only "dont know" and blank fields. This means that the RDT numbers still don't add up to the total. Is this how it should be?

**Comment by johnhaskew** [comment] 2016-10-27 08:34
Could we please create an additional column within the RDT block called _Don't Know / Missing_ and include these data here. The french translation would be: _Ne sait pas / Manquant_

**Closed** 2016-10-27 09:18 UTC
Labels: reports, Urgent
