### ISSUE TITLE
Afro report tests

### ISSUE THREAD

**Issue by Gulfa** [meerkat-code/meerkat_frontend#171] opened 2016-11-21 08:07 UTC
Write AFRO report tests

**Comment by mixmixmix** [comment] 2017-01-18 04:41
AFRO passes now most of the test. I have identified number of issues with report and test with which I need some assistance:
- [ ] - 1. Investigated cases of acute flaccid paralysis (`cmd_10`) are in code and document (AFRO dev plan spreadsheet) marked as `ale_2` which generally means "confirmed status". In the report `cmd_10_ale_2` reads "no of cases investigated". Should it be changed to `ale_1`?
- [ ] - 1. How cases of a given age are calculated? Entry with
                ```
                `"cmd_15":7,
                "age_5":5
                ```
Seems to produce only one case in the `figure_measles`. 
- [ ] - 3. Epi codes (e.g `epi_8`, severe malnutrition under 5) in a sole entry does not produce any values in the output. (list of malnutrition values is empty). It might be connected to the problems we experience with `epi_weekly` and `malaria_test`. `figure_malaria` and `figure_malnutrition` doesn't work for that reason. I need some help with understanding that.
- [ ] - 4.  Are we reporting cases of ILI in (%)? It was in the original plan document.
- [ ] - 5. If there are no registers submitted in a given week in a district, completeness call returns no information for that districts and therefore breaks the report.
- [ ] - 6. Completeness in AFRO report provides data for the last week even if report is meant to be generated for a past week. The cumulative completeness also takes into account data from the weeks in the future from report date. For example if on 30th-Dec we generate report 18-24-Dec it will contain completeness data as for the week 24-31-Dec.
- [ ] - 7. The yearly data will be invalid for the historical report from a previous year as it will use data for the current year instead of the year of the report.
- [ ] - 8. `ale_2` description should read "investigated and confirmed", `ale_1` - "investiged and *not* confirmed" .Those two codes are mutually exclusive.
- [ ] - 9. `['weekly_highlights']['malnutrition']` provides a breakdown of *severe* malnutrition cases by region. Table says "malnutrition" which implies both severe and moderate to be reported.
- [ ] - 10. In `table_priority_diseases`, should CFR be 0 when there are no cases instead of `N/A`?

**Comment by Gulfa** [comment] 2017-01-18 08:21
1. No of cases investigates should be ale_1 instead of ale_2, yes. 
2, As discussed cases should be just cmd_15: 1, age_5: 1
3. This sounds like a bug. Not sure why these cases are not showing up
4. @johnhaskew can you confirm if we should ILI ?
5. Can we just check the output from completeness and if the entry is empty just insert a 0 for completeness?
6. I think I fixed this in a new commit to development branch
7. This should also be fixed in the same commit
8. I do not think the codes are mutually exclusive. Any investigated case should have ale_1 and then all cases thare investigated and confirmed should have ale_2. 
9. @johnhaskew can you say if we should add the cases of moderate malnutrition here or just leave it as it is?
10. No, CFR is case fatality rate so we divided by number of cases. I think it therefore makes more sense to say N/A if ther aree no cases.

**Comment by mixmixmix** [comment] 2017-01-23 04:33
Frontend fix (point 1.) ready in https://github.com/meerkat-code/meerkat_frontend/tree/afro-correction after afro test is commited with changes to report.

Remaining issues are confirmations to point 4 and 9 and also
AFRO test needs more realistic fragmentation of test cases is `cases.py`.
For the point 5, should we create an issue to improve handling of completeness, or should I add exception handling to the report?

**Comment by mixmixmix** [comment] 2017-01-23 17:14
- Send an example of *4* to John
- *9* needs to be corrected in the report

**Comment by mixmixmix** [comment] 2017-01-27 04:28
After commenting (in either development (before NCD test broke the same test) or master branch):
```
        # Hack the tests for now.
        if app.config["TESTING"]:
            return {}
```
The API test fails on `test_all_urls`:
```
======================================================================
ERROR: test_all_urls (meerkat_api.test.MeerkatAPITestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/www/meerkat_api/meerkat_api/test/__init__.py", line 144, in test_all_urls
    rv = get_url(self.app, url)
  File "/var/www/meerkat_api/meerkat_api/test/__init__.py", line 114, in get_url
    rv = app.get(url, headers=settings.header)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/test.py", line 778, in get
    return self.open(*args, **kw)
  File "/usr/local/lib/python3.5/site-packages/flask/testing.py", line 127, in open
    follow_redirects=follow_redirects)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/test.py", line 751, in open
    response = self.run_wsgi_app(environ, buffered=buffered)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/test.py", line 668, in run_wsgi_app
    rv = run_wsgi_app(self.application, environ, buffered=buffered)
  File "/usr/local/lib/python3.5/site-packages/werkzeug/test.py", line 871, in run_wsgi_app
    app_rv = app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1994, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 271, in error_router
    return original_handler(e)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.5/site-packages/flask/_compat.py", line 32, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.5/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 477, in wrapper
    resp = resource(*args, **kwargs)
  File "/var/www/meerkat_api/meerkat_api/authentication.py", line 35, in decorated
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/flask_restful/__init__.py", line 587, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/var/www/meerkat_api/meerkat_api/resources/reports.py", line 2621, in get
    location, 4, end_date=end_date + timedelta(days=2)).data.decode('UTF-8'))
AttributeError: 'dict' object has no attribute 'data'
```
I have a problem because the print statements from the API are not showing in the log (`nosetests -v --nocapture meerkat_api.test.MeerkatAPITestCase`). Completeness works fine on demo site. Any thoughts? @jonathansberry @Gulfa

**Closed** 2017-02-15 07:38 UTC
